<a href="https://colab.research.google.com/github/Danangellotti/Ciencia_de_Datos_UGR_24/blob/main/Semana_03_Tema_01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [NumPy](https://numpy.org/doc/stable/reference/index.html) (Numerical Python)

Esta librería provee una forma eficiente de guardar y operar con buffers de datos densos. Por decirlo de algún modo, los NumPy array son como las listas de python pero optimizados para el almacenamiento y la operabilidad entre ellos.

Vamos a ver como se representa una variable en C y en Python.

![variable_c_python.png]()

Como podemos observar en C la variable contiene directamente el valor mientras que en python se tiene un objeto que almacena el valor.

Cuando queremos observar las listas pasa lo siguiente

![image.png]()

La representación de un numpy array es un objeto que contiene los valores de forma contigua y un lista es un objeto que almacena direcciones de memoria que contienen los valores. Por lo tanto cuando trabajamos con los numpy array estamos trabajando con los valores directamente y esto lo hace más eficiente.

## Instalación

```
!pip install numpy
```

## Versión

Para conocer la versión de NumPy o cualquier otra librería o módulo debemos mostrar la propiedad `__version__`

In [ ]:
import numpy as np
np.__version__

'1.22.4'

## Tipos de datos


| Tipo | Descripción |
| --- | --- |
| bool_ | Boolean (True or False) se almacena con byte |
| int_ | Por defecto es un entero (long en C) |
| intc | Identico al entero en C (normalmente int32 o int64) |
| intp | Entero usado para indexación (igual a C ssize_t; normalmente int32 o | int64) |
| int8 | Byte (–128 to 127) |
| int16 | Entero (–32768 to 32767) |
| int32 | Entero (–2147483648 to 2147483647) |
| int64 | Entero (–9223372036854775808 to 9223372036854775807) |
| uint8 | Entero sin signo (0 to 255) |
| uint16 | Entero sin signo (0 to 65535) |
| uint32 | Entero sin signo (0 to 4294967295) |
| uint64 | Entero sin signo (0 to 18446744073709551615) |
| float_ | Flotante float64 |
| float16 | Flotante de media precisión: signo 1 bit, 5 bits exponente, 10 bits mantisa |
| float32 | Flotante de simple precisión: signo 1 bit, 8 bits exponente, 23 bits mantisa |
| float64 | Flotante de doble precisión: signo 1 bit, 11 bits exponente, 52 bits mantisa |
| complex_ | Número complejo de complex128 |
| complex64 | Número complejo representado por 2 flotantes de 32 bits |
| complex128 | Número complejo representado por 2 flotantes de 64 bits |

## Array

Funciones para crear arreglos.

### Ceros

In [ ]:
# crea un arreglo de 10 posiciones con el valor 0 y el tipo entero
np.zeros(shape=10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# crea un arreglo de 10 posiciones con el valor 0 y el tipo flotante
np.zeros(shape=10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Unos

In [ ]:
# crea un arreglo de 10 posiciones con el valor 1 y el tipo entero
np.ones(shape=10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# crea un arreglo de 10 posiciones con el valor 0 y el tipo flotante
np.ones(shape=10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Desde lista

In [ ]:
# crea un arreglo a partir de los valores de una lista con el tipo flotante
# porque uno de sus valores es flotante
np.array(object=[1, 2.1, 3, 4, 5, 6])

array([1. , 2.1, 3. , 4. , 5. , 6. ])

### Valores equidistantes

In [ ]:
# crea un arreglo de 10 posiciones flotantes con el intervalor 0-3 dividivo 10 veces
np.linspace(start=0, stop=3, num=10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

### Valores random

In [ ]:
# crea un arreglo de 5 posiciones del tipo entero con valores aleatorios
# entre 0 y 10
np.random.randint(low=0, high=10, size=5)

array([8, 4, 6, 2, 6])

In [ ]:
# crea un arreglo de 5 posiciones de tipo flotante con valores aleatorios
# entre 0 y 1
np.random.random(size=5)

array([0.74796882, 0.39237859, 0.49318435, 0.4552831 , 0.84504901])

### Valores consecutivos

In [ ]:
# crea un arreglo de valores consecutivos que comienzan en 1 y terminan en 9
np.arange(start=1, stop=10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Matrices

Funciones para crear matrices. En este case se utilizan las mismas funciones pero cambia el argumento size al cual se le debe pasar una tupla indicando la cantidad de filas y columnas en ese orden.

### Ceros

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el valor 0 y el tipo entero
np.zeros(shape=(3,4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el valor 0 y el tipo flotante
np.zeros(shape=(3,4) , dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Unos

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el valor 1 y el tipo entero
np.ones(shape=(3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el valor 0 y el tipo flotante
np.ones(shape=(3,4) , dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Valores random

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el tipo entero y valores
# aleatorios entre 1 y 5
np.random.randint(low=1, high=5, size=(3,4))

array([[4, 4, 1, 2],
       [2, 4, 4, 1],
       [4, 4, 4, 3]])

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el tipo flotante y valores
# aleatorios entre 0 y 1
np.random.random(size=(3,4))

array([[0.64259466, 0.62357251, 0.33403526, 0.07926723],
       [0.58203142, 0.87939236, 0.68359884, 0.06396595],
       [0.18754822, 0.39723515, 0.49278229, 0.42637518]])

### Repetir mismo valor

In [ ]:
# crea una matriz de 3 filas y 4 columnas con el tipo flotante y en
# cada posición pone el número 3.14
np.full(shape=(3,4), fill_value=3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

### Matriz identidad

In [ ]:
# crea una matriz identidad de 4 filas y 4 columnas
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matriz con unos en una diagonal

In [ ]:
# crea una matriz donde la diagonal que comienza en la fila 0 y columna 0
# posee un valor 1
np.eye(N=3, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# crea una matriz donde la diagonal que comienza en la fila 0 y columna 0
# posee un valor 1
np.eye(N=3, M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# crea una matriz donde la diagonal que comienza en la fila 0 y columna 1
# posee un valor 1
np.eye(N=3, M=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matriz de 3 dimensiones

In [ ]:
# crea una matriz de 4 dimensiones, la primer dimensión tiene 3 matrices, la
# segunda dimensión tiene 4 matrices, la tercer dimensión tiene 2 filas y la
# cuarta dimensión tiene 3 columnas.
np.random.random(size=(3,4,2,3))

array([[[[0.17189787, 0.75496049, 0.4919113 ],
         [0.67471639, 0.89490823, 0.16242837]],

        [[0.80731224, 0.71785308, 0.38665694],
         [0.15935921, 0.0325678 , 0.50593774]],

        [[0.61916496, 0.06837115, 0.44957068],
         [0.17598463, 0.09317108, 0.331068  ]],

        [[0.61237029, 0.74958246, 0.22411221],
         [0.85679593, 0.21600464, 0.44461005]]],


       [[[0.73537555, 0.26764222, 0.50708422],
         [0.81536012, 0.29898897, 0.20222057]],

        [[0.60697626, 0.77238141, 0.35371246],
         [0.13402089, 0.24374479, 0.91963656]],

        [[0.74511783, 0.75688402, 0.58837017],
         [0.25926766, 0.83209609, 0.97418051]],

        [[0.95615465, 0.367616  , 0.62848844],
         [0.82248023, 0.85955387, 0.96992609]]],


       [[[0.17330478, 0.547962  , 0.85990299],
         [0.4214816 , 0.4656917 , 0.27531116]],

        [[0.44873246, 0.60125191, 0.87899962],
         [0.58944684, 0.71232323, 0.98805007]],

        [[0.16860814, 0.95629289, 0.02239244],
         [0.02083225, 0.55896261, 0.34049656]],

        [[0.99818431, 0.37132433, 0.9656855 ],
         [0.35993247, 0.96828959, 0.39484586]]]])

### Transposición de una matriz

In [ ]:
# creo una matriz de 3 filas y 4 columnas con valores aleatorios enteros que
# van del 1 al 11
matriz = np.random.randint(low=1, high=12, size=(3,4))
print("Matriz base de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: matriz.transpose()")
print("Matriz transpuesta desde una función.",
      matriz.transpose(), sep="\n")
print()
print("Sentencia: matriz.T")
print("Matriz transpuesta desde una propiedad.",
      matriz.T, sep="\n")

Matriz base de trabajo (matriz):
[[ 9  1  6 11]
 [10  7  2  6]
 [ 5  4  2  7]]

Sentencia: matriz.transpose()
Matriz transpuesta desde una función.
[[ 9 10  5]
 [ 1  7  4]
 [ 6  2  2]
 [11  6  7]]

Sentencia: matriz.T
Matriz transpuesta desde una propiedad.
[[ 9 10  5]
 [ 1  7  4]
 [ 6  2  2]
 [11  6  7]]

## Atributos, forma y copia

Los atributos son propiedades que puedo consultar para obtener información del
numpy array.
Los atributos son:
- La dimensión (ndim)
- El tamaño (size)
- El tipo de dato que único para el numpy array (dtype)
- El la forma del numpy array (shape)

In [ ]:
# creo una matriz de 5 filas y 5 columnas con valores consecutivos del 1 al 25
matriz = np.arange(start=1, stop=26).reshape((5, 5))
print("Matriz base de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: matriz.ndim")
print("Dimensiónes: ", matriz.ndim)
print()
print("Sentencia: matriz.size")
print("Tamaño: ", matriz.size)
print()
print("Sentencia: matriz.dtype")
print("Tipo: ", matriz.dtype)
print()
print("Sentencia: matriz.shape")
print("Forma: ", matriz.shape)

Matriz base de trabajo (matriz):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sentencia: matriz.ndim
Dimensiónes:  2

Sentencia: matriz.size
Tamaño:  25

Sentencia: matriz.dtype
Tipo:  int64

Sentencia: matriz.shape
Forma:  (5, 5)

### Cambiando la forma de un arreglo

El reshape siempre debe utilizar todas las posiciones del arreglo y me genera una matriz.

In [ ]:
# creo un arreglo de 10 posiciones con valores consecutivos del 0 al 9
arreglo_1 = np.arange(start=0, stop=10)
print("Arreglo base de trabajo (arreglo_1):", arreglo_1, sep="\n")
print()
print("Sentencia: arreglo_1.reshape((2, 5))")
print("Creo una matriz de 2 filas y 5 columnas:",
      arreglo_1.reshape((2, 5)), sep="\n")
print()
print("Sentencia: arreglo_1.reshape((5, 2))")
print("Creo una matriz de 5 filas y 2 columnas:",
      arreglo_1.reshape((5, 2)), sep="\n")
print()
print("Sentencia: arreglo_1.reshape((5, 2)).flatten()")
print("Paso de una matriz de 5 filas y 2 columnas a un arreglo:",
      arreglo_1.reshape((5, 2)).flatten(), sep="\n")

Arreglo base de trabajo (arreglo_1):
[0 1 2 3 4 5 6 7 8 9]

Sentencia: arreglo_1.reshape((2, 5))
Creo una matriz de 2 filas y 5 columnas:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Sentencia: arreglo_1.reshape((5, 2))
Creo una matriz de 5 filas y 2 columnas:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Sentencia: arreglo_1.reshape((5, 2)).flatten()
Paso de una matriz de 5 filas y 2 columnas a un arreglo:
[0 1 2 3 4 5 6 7 8 9]

### Copia

Para realizar la copia se utiliza la función copy que está optimizada.

Para verficar esto utilizamos la función id.

In [ ]:
matriz_copia = matriz.copy()
print("Matriz base de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: matriz.copy()", sep="\n")
print("Copia de la matriz (matriz_copia):", matriz_copia, sep="\n")
print()
print("Verificación de los id de los objetos para visualizar que son distintos.")
print("id(matriz):       ", id(matriz))
print("id(matriz_copia): ", id(matriz_copia))

Matriz base de trabajo (matriz):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sentencia: matriz.copy()
Copia de la matriz (matriz_copia):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Verificación de los id de los objetos para visualizar que son distintos.
id(matriz):        140189481572944
id(matriz_copia):  140189481574000

## Acceso a los datos

Vamos a ver las distintas formas que tengo para acceder a los datos de un numpy array.

### Por posición

Para poder acceder se le pueden pasar valores fijos de fila y columna.

In [ ]:
print("Matriz base de trabajo (matriz): \n", matriz)
print()
print("Sentencia: matriz[0]")
print("Accedo a la fila 0 y obtengo el numpy array:", matriz[0], sep="\n")
print()
print("Sentencia: matriz[0, 2]")
print("Accedo a la fila 0 y columna 2 y obtengo el valor:",
      matriz[0, 2], sep="\n")
print()
print("Sentencia: matriz[0][2]")
print("Accedo a la fila 0 y columna 2 y obtengo el valor:",
      matriz[0][2], sep="\n")
print()
print("Sentencia: matriz.flatten[8]")
print("La función 'flatten' me devuelve un arreglo que une las filas.")
print("Accedo a un valor que esta en la posición 8 pero el acceso se realiza \n"
      "sobre un arreglo.", matriz.flatten()[8], sep="\n")
print()
print("Sentencia: matriz.flatten()")
print("Muestra del flat de la matriz: ", matriz.flatten())

Matriz base de trabajo (matriz):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sentencia: matriz[0]
Accedo a la fila 0 y obtengo el numpy array:
[1 2 3 4 5]

Sentencia: matriz[0, 2]
Accedo a la fila 0 y columna 2 y obtengo el valor:
3

Sentencia: matriz[0][2]
Accedo a la fila 0 y columna 2 y obtengo el valor:
3

Sentencia: matriz.flatten[8]
La función 'flatten' me devuelve un arreglo que une las filas.
Accedo a un valor que esta en la posición 8 pero el acceso se realiza
sobre un arreglo.
9

Sentencia: matriz.flatten()
Muestra del flat de la matriz:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

### Por slicing

Siempre se hace desde el índice inferior incluido hasta el índice superior sin incluir.

Se pueden usar valores negativos donde se comienza desde el final hacia adelante.

El slicing puede tener 3 parámetros `indice_inferior:indice_superior:paso_o_incremento`.
- indice_inferior: es inclusivo.
- indice_superior: no se incluye.
- paso_o_incremento: por defecto es 1.

In [ ]:
print("Matriz base de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: matriz[1:3]")
print("Obtengo todas las filas que son mayores o iguales a 1 y menores que 3.\n"\
      "Se muestran las filas 1 y 2.",  matriz[1:3], sep="\n")
print()
print("Sentencia: matriz[:,2]")
print("Obtengo todas las filas de la columna 2.", matriz[:,2], sep="\n")
print()
print("Sentencia: matriz[:,1:3]")
print("Obtengo todas las filas y todas las columnas que son mayores o iguales \n"\
      "a 1 y menores que 3. Se muestran las columnas 1 y 2.",
      matriz[:,1:3], sep="\n")
print()
print("Sentencia: matriz[::2]")
print("Obtengo todas las filas con un incremento de 2. Se muestran las filas\n"\
      "pares o las filas 0,2,4 y todas las columnas.", matriz[::2], sep="\n")
print()
print("Sentencia: matriz[::2,::2]")
print("Obtengo todas las filas con un incremento de 2 y todas las columnas\n"\
      "con un incremento de 2. Se muestran las filas pares o las filas 0,2,4 y\n"\
      "las columnas pares o las columnas 0,2,4.", matriz[::2,::2], sep="\n")

Matriz base de trabajo (matriz):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sentencia: matriz[1:3]
Obtengo todas las filas que son mayores o iguales a 1 y menores que 3.
Se muestran las filas 1 y 2.
[[ 6  7  8  9 10]
 [11 12 13 14 15]]

Sentencia: matriz[:,2]
Obtengo todas las filas de la columna 2.
[ 3  8 13 18 23]

Sentencia: matriz[:,1:3]
Obtengo todas las filas y todas las columnas que son mayores o iguales
a 1 y menores que 3. Se muestran las columnas 1 y 2.
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]

Sentencia: matriz[::2]
Obtengo todas las filas con un incremento de 2. Se muestran las filas
pares o las filas 0,2,4 y todas las columnas.
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]

Sentencia: matriz[::2,::2]
Obtengo todas las filas con un incremento de 2 y todas las columnas
con un incremento de 2. Se muestran las filas pares o las filas 0,2,4 y
las columnas pares o las columnas 0,2,4.
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]

### Por índices

Se accede a los valores de la matriz por arreglos de indices. En lugar de pasar una posición fija se pasan un arreglo de posiciones.

In [ ]:
# obtengo la cantidad de filas de la matriz
print("Cantidad de filas de la matriz:", matriz.shape[0], sep="\n")
print("Cantidad de columnas de la matriz:", matriz.shape[1], sep="\n")
print()
indices_filas = np.arange(start=0, stop=matriz.shape[0])
indices_columnas = np.arange(start=0, stop=matriz.shape[1])
indices_filas_invertidos = indices_filas[::-1]
indices_columnas_invertidos = indices_columnas[::-1]
print("Sentencia: np.arange(start=0, stop=matriz.shape[0])")
print("Creo el arreglo indices para las filas:", indices_filas, sep="\n")
print("Sentencia: np.arange(start=0, stop=matriz.shape[1])")
print("Creo el arreglo indices para las columnas:", indices_columnas, sep="\n")
print("Sentencia: indices_filas[::-1]")
print("Creo el arreglo indices para las filas invertido:",
      indices_filas_invertidos, sep="\n")
print("Sentencia: indices_columnas[::-1]")
print("Creo el arreglo indices para las columnas invertido:",
      indices_columnas_invertidos, sep="\n")
print()
print("Matriz base de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: matriz[indices_filas, indices_columnas]")
print(f"Muestro la diagonal que va desde la posición [0,0] hasta la posición \n"\
      f"[{matriz.shape[0]},{matriz.shape[1]}]:",
      matriz[indices_filas, indices_columnas], sep="\n")
print()
print("Sentencia: matriz[indices_filas, indices_columnas_invertidos]")
print(f"Muestro la diagonal que va desde la posición [0,{matriz.shape[1]}] \n"\
      f"hasta la posición :[{matriz.shape[0]},0]:",
      matriz[indices_filas, indices_columnas_invertidos], sep="\n")
print()
print("Sentencia: matriz[indices_filas_invertidos, indices_columnas_invertidos]")
print(f"Muestro la diagonal que va desde la posición [{matriz.shape[0]},{matriz.shape[1]}] \n"\
      f"hasta la posición :[0,0]:",
      matriz[indices_filas_invertidos, indices_columnas_invertidos], sep="\n")
print()
print("Sentencia: matriz[indices_filas_invertidos, indices_columnas]")
print(f"Muestro la diagonal que va desde la posición [{matriz.shape[0]},0] \n"\
      f"hasta la posición :[0,{matriz.shape[1]}]:",
      matriz[indices_filas_invertidos, indices_columnas], sep="\n")

Cantidad de filas de la matriz:
5
Cantidad de columnas de la matriz:
5

Sentencia: np.arange(start=0, stop=matriz.shape[0])
Creo el arreglo indices para las filas:
[0 1 2 3 4]
Sentencia: np.arange(start=0, stop=matriz.shape[1])
Creo el arreglo indices para las columnas:
[0 1 2 3 4]
Sentencia: indices_filas[::-1]
Creo el arreglo indices para las filas invertido:
[4 3 2 1 0]
Sentencia: indices_columnas[::-1]
Creo el arreglo indices para las columnas invertido:
[4 3 2 1 0]

Matriz base de trabajo (matriz):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sentencia: matriz[indices_filas, indices_columnas]
Muestro la diagonal que va desde la posición [0,0] hasta la posición
[5,5]:
[ 1  7 13 19 25]

Sentencia: matriz[indices_filas, indices_columnas_invertidos]
Muestro la diagonal que va desde la posición [0,5]
hasta la posición :[5,0]:
[ 5  9 13 17 21]

Sentencia: matriz[indices_filas_invertidos, indices_columnas_invertidos]
Muestro la diagonal que va desde la posición [5,5]
hasta la posición :[0,0]:
[25 19 13  7  1]

Sentencia: matriz[indices_filas_invertidos, indices_columnas]
Muestro la diagonal que va desde la posición [5,0]
hasta la posición :[0,5]:
[21 17 13  9  5]

## Broadcasting

Es la multidifusión de los objetos para poder operar con matrices. Esto me permite realizar operaciones entre una matriz NxM y

- Un entero
- Un arreglo
- Una matriz 1xM
- Una matriz Nx1

Python se encarga de generar nuevas matrices para poder operar de forma correcta.

`El broadcasting se realiza siempre!`

In [ ]:
# creo una matriz de 3 filas y 3 columnas
matriz = np.arange(start=1, stop=10).reshape((3, 3))
print("Matriz de trabajo (matriz):", matriz, sep="\n")

print()
print("Sentencia: np.add(matriz, 2)")
print("Suma de una matriz con un entero.",
      np.add(matriz, 2), sep="\n")
print("El valor 2 se transforma en la siguiente matriz ",
      [[2, 2, 2], [2, 2, 2], [2, 2, 2]], sep="\n")

print()
print("Sentencia: np.add(matriz, [10, 20, 30])")
print("Suma de una matriz y un vector.",
      np.add(matriz, [10, 20, 30]), sep="\n")
print("El vector [10, 20, 30] se transforma en la siguiente matriz ",
      [[10, 20, 30], [10, 20, 30], [10, 20, 30]], sep="\n")
print("IMPORTANTE: El arreglo debe tener la misma cantidad de columnas que la matriz.")

print()
print("Sentencia: np.add(matriz, [[100, 200, 300]])")
print("Suma de una matriz con otra matriz que posee solo 1 fila.",
      np.add(matriz, [[100, 200, 300]]), sep="\n")
print("Esta matriz [[100, 200, 300]] se transforma en la siguiente matriz",
      [[100, 200, 300], [100, 200, 300], [100, 200, 300]], sep="\n")
print("IMPORTANTE: Ambas matrices deben tener la misma cantidad de columnas")

print()
print("Sentencia: np.add(matriz, [[1000], [2000], [3000]])")
print("Suma de una matriz con otra matriz que solo posee 1 valor en cada fila.",
      np.add(matriz, [[1000], [2000], [3000]]), sep="\n")
print("Esta matriz [[1000], [2000], [3000]] se transforma en la siguiente matriz",
      [[1000, 1000, 1000],[2000, 2000, 2000],[3000, 3000, 3000]], sep="\n")
print("IMPORTANTE: Ambas matrices deben tener la misma cantidad de filas.")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.add(matriz, 2)
Suma de una matriz con un entero.
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
El valor 2 se transforma en la siguiente matriz
[[2, 2, 2], [2, 2, 2], [2, 2, 2]]

Sentencia: np.add(matriz, [10, 20, 30])
Suma de una matriz y un vector.
[[11 22 33]
 [14 25 36]
 [17 28 39]]
El vector [10, 20, 30] se transforma en la siguiente matriz
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]
IMPORTANTE: El arreglo debe tener la misma cantidad de columnas que la matriz.

Sentencia: np.add(matriz, [[100, 200, 300]])
Suma de una matriz con otra matriz que posee solo 1 fila.
[[101 202 303]
 [104 205 306]
 [107 208 309]]
Esta matriz [[100, 200, 300]] se transforma en la siguiente matriz
[[100, 200, 300], [100, 200, 300], [100, 200, 300]]
IMPORTANTE: Ambas matrices deben tener la misma cantidad de columnas

Sentencia: np.add(matriz, [[1000], [2000], [3000]])
Suma de una matriz con otra matriz que solo posee 1 valor en cada fila.
[[1001 1002 1003]
 [2004 2005 2006]
 [3007 3008 3009]]
Esta matriz [[1000], [2000], [3000]] se transforma en la siguiente matriz
[[1000, 1000, 1000], [2000, 2000, 2000], [3000, 3000, 3000]]
IMPORTANTE: Ambas matrices deben tener la misma cantidad de filas.

## Unión de arreglos y matrices

Para unir arreglo vamos a utilizar la función `concatenate` que recibe como parámetro un objeto iterable de numpy array a concatenar y la dirección en que lo deseo hacer. Para la dirección se utiliza el argumento `axis`.

In [ ]:
# vamos a generar arreglos y matrices que utilizaremos más adelante
arreglo = np.arange(start=0, stop=12)
arreglo_1 = np.arange(start=1, stop=4)
arreglo_2 = np.arange(start=4, stop=7)

matriz_1 = np.arange(start=1, stop=7).reshape((2,3))
matriz_2 = np.arange(start=11, stop=17).reshape((2,3))
matriz_grande = np.concatenate([matriz_1, matriz_2])
matriz_grande = np.concatenate([matriz_grande, np.multiply(matriz_grande, 2)[::-1]])
matriz_grande = np.concatenate([matriz_grande, matriz_grande[::-1]], axis=1)

### Unión de arreglos

In [ ]:
print("Arreglo de trabajo (arreglo_1): \n", arreglo_1)
print("Arreglo de trabajo (arreglo_2): \n", arreglo_2)
print()
print("Sentencia: np.concatenate((arreglo_1, arreglo_2))")
print("Arreglos concatenados.",
      np.concatenate((arreglo_1, arreglo_2)), sep="\n")

Arreglo de trabajo (arreglo_1):
 [1 2 3]
Arreglo de trabajo (arreglo_2):
 [4 5 6]

Sentencia: np.concatenate((arreglo_1, arreglo_2))
Arreglos concatenados.
[1 2 3 4 5 6]

### Unión de matrices

Tener cuidado con las dimensiones de las matrices:
- Si se agregan filas entonces deben poseer la misma cantidad de columnas.
- Si se agregan columnas entonces deben poseer la misma cantidad de filas.

In [ ]:
print("Matriz de trabajo (matriz_1):", matriz_1, sep="\n")
print("Matriz de trabajo (matriz_2):", matriz_2, sep="\n")
print()
print("Sentencia: np.concatenate((matriz_1, matriz_2))")
print("Matrices concatenadas agregando filas.",
      np.concatenate((matriz_1, matriz_2)), sep="\n")
print()
print("Sentencia: np.concatenate((matriz_1, matriz_2), axis=1)")
print("Matrices concatenadas agregando columnas.",
      np.concatenate((matriz_1, matriz_2), axis=1), sep="\n")

Matriz de trabajo (matriz_1):
[[1 2 3]
 [4 5 6]]
Matriz de trabajo (matriz_2):
[[11 12 13]
 [14 15 16]]

Sentencia: np.concatenate((matriz_1, matriz_2))
Matrices concatenadas agregando filas.
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]

Sentencia: np.concatenate((matriz_1, matriz_2), axis=1)
Matrices concatenadas agregando columnas.
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]

### Unión de arreglos y matrices

Para unir arreglos y matrices vamos a utilizar las siguientes funciones:
- `vstack`: poniendo el arreglo como una nueva fila.
- `hstack`: poniendo el arreglo como una nueva columna.


Tener cuidado con las dimensiones de las matrices:
- Si se agregan filas entonces deben poseer la misma cantidad de columnas.
- Si se agregan columnas entonces deben poseer la misma cantidad de filas.

In [ ]:
print("Arreglo de trabajo (arreglo_1):", arreglo_1, sep="\n")
print("Matriz de trabajo (matriz_2):", matriz_2, sep="\n")
print()
print("Sentencia: np.vstack((arreglo_1, matriz_2))")
print("Concatenación de matriz y arreglo por fila.",
      np.vstack((arreglo_1, matriz_2)), sep="\n")
print()
print("Necesito cambiar la forma del arreglo 1 para poder concatenarlos.")
arreglo_tmp = arreglo_1[0:2].reshape(2,1)
print("La nueva forma es [2,1]:", arreglo_tmp, sep="\n")
print()
print("Sentencia: np.hstack((arreglo_tmp, matriz_2))")
print("Concatenación de matriz y arreglo por columna.",
      np.hstack((arreglo_tmp, matriz_2)), sep="\n")

Arreglo de trabajo (arreglo_1):
[1 2 3]
Matriz de trabajo (matriz_2):
[[11 12 13]
 [14 15 16]]

Sentencia: np.vstack((arreglo_1, matriz_2))
Concatenación de matriz y arreglo por fila.
[[ 1  2  3]
 [11 12 13]
 [14 15 16]]

Necesito cambiar la forma del arreglo 1 para poder concatenarlos.
La nueva forma es [2,1]:
[[1]
 [2]]

Sentencia: np.hstack((arreglo_tmp, matriz_2))
Concatenación de matriz y arreglo por columna.
[[ 1 11 12 13]
 [ 2 14 15 16]]

## Separación de arreglos y matrices

### Separación de un arreglo por índices

Para realizar la separación se utiliza la función `split` y el corte lo realiza para índices. Esta función recibe como parámetro un arreglo y una objeto iterable con los valores de los índices para realizar las separaciones.

In [ ]:
arreglo_tmp = np.arange(start=0, stop=12)
x_1, x_2, x_3, x_4 = np.split(arreglo_tmp, (3, 5, 8))

print("Arreglo de trabajo (arreglo_tmp):", arreglo_tmp, sep="\n")
print()
print("Sentencia: np.split(arreglo_tmp, (3, 5, 8))")
print()
print("x_1 (desde el índice 0 hasta el índice 3):", x_1, sep="\n")
print()
print("x_2 (desde el índice 3 hasta el índice 5):", x_2, sep="\n")
print()
print("x_3 (desde el índice 5 hasta el índice 8):", x_3, sep="\n")
print()
print("x_4 (desde el índice 8 hasta el final):", x_4, sep="\n")

Arreglo de trabajo (arreglo_tmp):
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Sentencia: np.split(arreglo_tmp, (3, 5, 8))

x_1 (desde el índice 0 hasta el índice 3):
[0 1 2]

x_2 (desde el índice 3 hasta el índice 5):
[3 4]

x_3 (desde el índice 5 hasta el índice 8):
[5 6 7]

x_4 (desde el índice 8 hasta el final):
[ 8  9 10 11]

### Separación de una matriz por filas

Para realizar la separación se utiliza la función `vsplit` y el corte lo realiza para índices. Esta función recibe como parámetro un matriz y una objeto iterable con los valores de los índices para realizar las separaciones.

In [ ]:
x_1, x_2, x_3, x_4 = np.vsplit(matriz_grande, (1, 3, 5))

print("Matriz de trabajo (matriz_grande):", matriz_grande, sep="\n")
print()
print("Sentencia: np.vsplit(matriz_tmp, (1, 3, 5))")
print()
print("x_1 (desde el índice 0 hasta el índice 1):", x_1, sep="\n")
print()
print("x_2 (desde el índice 1 hasta el índice 3):", x_2, sep="\n")
print()
print("x_3 (desde el índice 3 hasta el índice 5):", x_3, sep="\n")
print()
print("x_4 (desde el índice 5 hasta el final):", x_4, sep="\n")

Matriz de trabajo (matriz_grande):
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [11 12 13 22 24 26]
 [14 15 16 28 30 32]
 [28 30 32 14 15 16]
 [22 24 26 11 12 13]
 [ 8 10 12  4  5  6]
 [ 2  4  6  1  2  3]]

Sentencia: np.vsplit(matriz_tmp, (1, 3, 5))

x_1 (desde el índice 0 hasta el índice 1):
[[1 2 3 2 4 6]]

x_2 (desde el índice 1 hasta el índice 3):
[[ 4  5  6  8 10 12]
 [11 12 13 22 24 26]]

x_3 (desde el índice 3 hasta el índice 5):
[[14 15 16 28 30 32]
 [28 30 32 14 15 16]]

x_4 (desde el índice 5 hasta el final):
[[22 24 26 11 12 13]
 [ 8 10 12  4  5  6]
 [ 2  4  6  1  2  3]]

### Separación de una matriz por columnas

Para realizar la separación se utiliza la función `hsplit` y el corte lo realiza para índices. Esta función recibe como parámetro un matriz y una objeto iterable con los valores de los índices para realizar las separaciones.

In [ ]:
x_1, x_2, x_3, x_4 = np.hsplit(matriz_grande, (1, 3, 5))
print("Matriz de trabajo (matriz_grande):", matriz_grande, sep="\n")
print()
print("Sentencia: np.hsplit(matriz_grande, (1, 3, 5))")
print()
print("x_1 (desde el índice 0 hasta el índice 1):", x_1, sep="\n")
print()
print("x_2 (desde el índice 1 hasta el índice 3):", x_2, sep="\n")
print()
print("x_3 (desde el índice 3 hasta el índice 5):", x_3, sep="\n")
print()
print("x_4 (desde el índice 5 hasta el final):", x_4, sep="\n")

Matriz de trabajo (matriz_grande):
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [11 12 13 22 24 26]
 [14 15 16 28 30 32]
 [28 30 32 14 15 16]
 [22 24 26 11 12 13]
 [ 8 10 12  4  5  6]
 [ 2  4  6  1  2  3]]

Sentencia: np.hsplit(matriz_grande, (1, 3, 5))

x_1 (desde el índice 0 hasta el índice 1):
[[ 1]
 [ 4]
 [11]
 [14]
 [28]
 [22]
 [ 8]
 [ 2]]

x_2 (desde el índice 1 hasta el índice 3):
[[ 2  3]
 [ 5  6]
 [12 13]
 [15 16]
 [30 32]
 [24 26]
 [10 12]
 [ 4  6]]

x_3 (desde el índice 3 hasta el índice 5):
[[ 2  4]
 [ 8 10]
 [22 24]
 [28 30]
 [14 15]
 [11 12]
 [ 4  5]
 [ 1  2]]

x_4 (desde el índice 5 hasta el final):
[[ 6]
 [12]
 [26]
 [32]
 [16]
 [13]
 [ 6]
 [ 3]]

## Comparaciones


| Operador | Función |
| --- | --- |
| == | np.equal |
| != | np.not_equal |
| < | np.less |
| <= | np.less_equal |
| > | np.greater |
| >= | np.greater_equal |

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.less(matriz, 4)")
print("Obtener que valores son menores a 4.", np.less(matriz, 4), sep="\n")
print()
print("Sentencia: np.equal(np.mod(matriz,2), 0)")
print("Obtener que valores son multiplos de 2.",
      np.equal(np.mod(matriz,2), 0), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.less(matriz, 4)
Obtener que valores son menores a 4.
[[ True  True  True]
 [False False False]
 [False False False]]

Sentencia: np.equal(np.mod(matriz,2), 0)
Obtener que valores son multiplos de 2.
[[False  True False]
 [ True False  True]
 [False  True False]]

### Operadores booleanos

Estos operadores se utilizan para realizar operaciones booleanos.

| Operador | Función | Descripción |
| --- | --- | --- |
| & | np.bitwise_and | Operación `y` |
| &#124; | np.bitwise_or | Operación `o` |
| ^ | np.bitwise_xor | Operación `xor` |
| ~ | np.bitwise_not | Operación de negación |

> Tablas de verdad de los operadores

- Negación

| Valor | Negación |
| --- | --- |
| True | False |
| False | True |

- Y

| Valor 1 | Valor 2 | Resultado |
| --- | --- | --- |
| True | True | True |
| True | False | False |
| False | False | False |
| False | True | False |

- O

| Valor 1 | Valor 2 | Resultado |
| --- | --- | --- |
| True | True | True |
| True | False | True |
| False | False | False |
| False | True | True |

- XOR

| Valor 1 | Valor 2 | Resultado |
| --- | --- | --- |
| True | True | False |
| True | False | True |
| False | False | False |
| False | True | True |

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
matriz_menores_a_4 = np.less(matriz, 4)
matriz_mayores_a_7 = np.greater(matriz, 7)
matriz_modulo_de_2 = np.mod(matriz, 2)
matriz_modulo_de_3 = np.mod(matriz, 3)
matriz_modulo_de_2_igual_0 = np.equal(np.mod(matriz, 2), 0)
matriz_modulo_de_3_igual_0 = np.equal(np.mod(matriz, 3), 0)
print("Matriz de trabajo (matriz_menores_a_4):", matriz_menores_a_4, sep="\n")
print("Matriz de trabajo (matriz_mayores_a_7):", matriz_mayores_a_7, sep="\n")
print("Matriz de trabajo (matriz_modulo_de_2):", matriz_modulo_de_2, sep="\n")
print("Matriz de trabajo (matriz_modulo_de_3):", matriz_modulo_de_3, sep="\n")
print("Matriz de trabajo (matriz_modulo_de_2_igual_0):",
      matriz_modulo_de_2_igual_0, sep="\n")
print("Matriz de trabajo (matriz_modulo_de_3_igual_0):",
      matriz_modulo_de_3_igual_0, sep="\n")
print()
print("Sentencia: np.bitwise_or(matriz_menores_a_4, matriz_mayores_a_7)")
print("Matriz de verdad de valores menores que 4 o mayores a 8:",
      np.bitwise_or(matriz_menores_a_4, matriz_mayores_a_7), sep="\n")
print()
print("Sentencia: np.bitwise_and(matriz_modulo_de_2_igual_0, matriz_modulo_de_3_igual_0)")
print("Matriz de verdad de valores que son múltiplos de 2 y múltiplos 3 ambos a la vez: ",
      np.bitwise_and(matriz_modulo_de_2_igual_0, matriz_modulo_de_3_igual_0), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz de trabajo (matriz_menores_a_4):
[[ True  True  True]
 [False False False]
 [False False False]]
Matriz de trabajo (matriz_mayores_a_7):
[[False False False]
 [False False False]
 [False  True  True]]
Matriz de trabajo (matriz_modulo_de_2):
[[1 0 1]
 [0 1 0]
 [1 0 1]]
Matriz de trabajo (matriz_modulo_de_3):
[[1 2 0]
 [1 2 0]
 [1 2 0]]
Matriz de trabajo (matriz_modulo_de_2_igual_0):
[[False  True False]
 [ True False  True]
 [False  True False]]
Matriz de trabajo (matriz_modulo_de_3_igual_0):
[[False False  True]
 [False False  True]
 [False False  True]]

Sentencia: np.bitwise_or(matriz_menores_a_4, matriz_mayores_a_7)
Matriz de verdad de valores menores que 4 o mayores a 8:
[[ True  True  True]
 [False False False]
 [False  True  True]]

Sentencia: np.bitwise_and(matriz_modulo_de_2_igual_0, matriz_modulo_de_3_igual_0)
Matriz de verdad de valores que son múltiplos de 2 y múltiplos 3 ambos a la vez:
[[False False False]
 [False False  True]
 [False False False]]

### Función where

La función verifica si se cumple o no con una condición o comparación sobre un numpy array.

Tiene 2 respuestas:
- En caso de pasar un numpy array booleano retorna los indices de los valores que son verdaderos.
- En caso de numpy array y las condiciones `x` e `y` retorna el valor de la posición en `x` si es verdader y el valor de la posición en `y` si es falso.

In [ ]:
arreglo_where = np.arange(start=10, stop=22)
print("Arreglo de trabajo (arreglo_where):", arreglo_where, sep="\n")
print()
arreglo_modulo_2 = np.equal(np.mod(arreglo_where, 2), 0)
print("Arreglo de trabajo (arreglo_modulo_2):", arreglo_modulo_2, sep="\n")
print()
print("Sentencia: np.where(arreglo_modulo_2)")
print("Retorna los Índices que cumplen con la condición que sean módulo de 2.",
      np.where(arreglo_modulo_2), sep="\n")
print()
print("Sentencia: np.where(arreglo_menores_a_3, arreglo_where, -1)")
print("Agrego las condiciones x e y para los valores que sean módulo de 2.",
      "- Si la condición se cumple, entonces completa con el valor correspondiente que se está analizando.",
      "- Si la condición NO se cumple, entonces completa con -1",
      np.where(arreglo_modulo_2, arreglo_where, -1), sep="\n")
print()
print("Sentencia: np.where(arreglo_menores_a_3, -1, arreglo_where)")
print("Agrego las condiciones x e y para los valores que sean módulo de 2. ",
      "- Si la condición se cumple, entonces completa con -1",
      "- Si la condición NO se cumple, entonces completa con el valor correspondiente que se está analizando.",
      np.where(arreglo_modulo_2, -1, arreglo_where), sep="\n")

Arreglo de trabajo (arreglo_where):
[10 11 12 13 14 15 16 17 18 19 20 21]

Arreglo de trabajo (arreglo_modulo_2):
[ True False  True False  True False  True False  True False  True False]

Sentencia: np.where(arreglo_modulo_2)
Retorna los Índices que cumplen con la condición que sean módulo de 2.
(array([ 0,  2,  4,  6,  8, 10]),)

Sentencia: np.where(arreglo_menores_a_3, arreglo_where, -1)
Agrego las condiciones x e y para los valores que sean módulo de 2.
- Si la condición se cumple, entonces completa con el valor correspondiente que se está analizando.
- Si la condición NO se cumple, entonces completa con -1
[10 -1 12 -1 14 -1 16 -1 18 -1 20 -1]

Sentencia: np.where(arreglo_menores_a_3, -1, arreglo_where)
Agrego las condiciones x e y para los valores que sean módulo de 2.
- Si la condición se cumple, entonces completa con -1
- Si la condición NO se cumple, entonces completa con el valor correspondiente que se está analizando.
[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21]

## Funciones para realizar operaciones básicas

Están optimizadas para ejecutarse de forma más eficiente y rápida.

Se pueden realizar entre matrices, arreglos o enteros.

Tener en cuenta que la posición en que se pasan los parámetros es importante para las operaciones que no son conmutativas.

Vamos a listar las operaciones más comunes.

| Operador python | Función NumPy | Descipción |
| --- | --- | --- |
| + | np.add | Suma |
| - | np.subtract | Resta |
| - | np.negative | Negación o inversión de signo |
| * | np.multiply | Multiplicación |
| / | np.divide | División |
| // | np.floor_divide | División entera |
| ** | np.power | Potencia |
| % | np.mod | Módulo de la división |
| abs | np.absolute o np.abs | Valor absoluto |
| seno | np.sin | Calcula el seno de los valores |
| coseno | np.con | Calcula el coseno de los valores |
| tangente | np.tan | Calcula el tangente de los valores |
| log | np.log | Calcula el logaritmo|
| log2 | np.log2 | Calcula el logaritmo en base 2 |
| log10 | np.log10 | Calcula el logaritmo en base 10 |

In [ ]:
# Suma
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.add(2, matriz)")
print("Suma de un entero y una matriz.", np.add(2, matriz), sep="\n")
print()
print("Sentencia: np.add(matriz, 2)")
print("Suma de una matriz y un entero.",
      np.add(matriz, 2), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.add(2, matriz)
Suma de un entero y una matriz.
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Sentencia: np.add(matriz, 2)
Suma de una matriz y un entero.
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [ ]:
# Resta
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.substract(2, matriz)")
print("Resta de un entero y una matriz.",
      np.subtract(2, matriz), sep="\n")
print()
print("Sentencia: np.subtract(matriz, 2)")
print("Resta de una matriz y un entero.",
      np.subtract(matriz, 2), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.substract(2, matriz)
Resta de un entero y una matriz.
[[ 1  0 -1]
 [-2 -3 -4]
 [-5 -6 -7]]

Sentencia: np.subtract(matriz, 2)
Resta de una matriz y un entero.
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

In [ ]:
# suma de booleanos, suma todos los valores que se encuentra en True
matriz_where = np.arange(start=10, stop=19).reshape(3,3)
print("Matriz de trabajo (matriz_where):", matriz_where, sep="\n")
print()
matriz_less_17 = np.less(matriz_where, 17)
print("Sentencia: np.less(matriz, 17)")
print("Matriz con valores menores a 7 (matriz_less_17):",
      matriz_less_17, sep="\n")
print()
print("Sentencia: np.where(matriz_less_17)")
print("Índices que cumplen con la condición que sean menores a 17. En este caso\n"\
      "caso el primer array son las filas y el segundo array son la columnas.",
      np.where(matriz_less_17), sep="\n")
print()
print("Sentencia: np.where(matriz_less_17, matriz_where, -1)")
print("Agrego las condiciones x e y para los valores que sean menores de 17.",
      "- Si la condición se cumple, entonces completa con el valor\n"\
      "  correspondiente que se está analizando.",
      "- Si la condición NO se cumple, entonces completa con -1",
      np.where(matriz_less_17, matriz_where, -1), sep="\n")
print()
print("Sentencia: np.where(matriz_less_17, -1, matriz_where)")
print("Agrego las condiciones x e y para los valores que sean menores de 17.",
      "- Si la condición se cumple, entonces completa con -1",
      "- Si la condición NO se cumple, entonces completa con el valor\n"\
      "  correspondiente que se está analizando.",
      np.where(matriz_less_17, -1, matriz_where), sep="\n")

Matriz de trabajo (matriz_where):
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Sentencia: np.less(matriz, 17)
Matriz con valores menores a 7 (matriz_less_17):
[[ True  True  True]
 [ True  True  True]
 [ True False False]]

Sentencia: np.where(matriz_less_17)
Índices que cumplen con la condición que sean menores a 17. En este caso
caso el primer array son las filas y el segundo array son la columnas.
(array([0, 0, 0, 1, 1, 1, 2]), array([0, 1, 2, 0, 1, 2, 0]))

Sentencia: np.where(matriz_less_17, matriz_where, -1)
Agrego las condiciones x e y para los valores que sean menores de 17.
- Si la condición se cumple, entonces completa con el valor
  correspondiente que se está analizando.
- Si la condición NO se cumple, entonces completa con -1
[[10 11 12]
 [13 14 15]
 [16 -1 -1]]

Sentencia: np.where(matriz_less_17, -1, matriz_where)
Agrego las condiciones x e y para los valores que sean menores de 17.
- Si la condición se cumple, entonces completa con -1
- Si la condición NO se cumple, entonces completa con el valor
  correspondiente que se está analizando.
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 17 18]]

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.substract(2, matriz, where=np.equal(np.mod(matriz,3),0)",
      "Resta 2 cuando la posición es multiplo de 3, en caso contrario pone el valor de la operación <valor>%3",
      np.subtract(2, matriz, where=np.equal(np.mod(matriz,3),0)), sep="\n")
print()
print("Sentencia: np.where(np.equal(np.mod(matriz,3),0), np.subtract(2,matriz),0)",
      "Resta 2 cuando la posición es multiplo de 3, en caso contrario pone 0",
      np.where(np.equal(np.mod(matriz,3),0), np.subtract(2,matriz),0), sep="\n")

matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.substract(2, matriz, where=np.equal(np.mod(matriz,3),0)
Resta 2 cuando la posición es multiplo de 3, en caso contrario pone el valor de la operación <valor>%3
[[ 1  2 -1]
 [ 1  2 -4]
 [ 1  2 -7]]

Sentencia: np.where(np.equal(np.mod(matriz,3),0), np.subtract(2,matriz),0)
Resta 2 cuando la posición es multiplo de 3, en caso contrario pone 0
[[ 0  0 -1]
 [ 0  0 -4]
 [ 0  0 -7]]

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
matriz_tmp = np.equal(np.mod(matriz, 3), 0)
print("Sentencia: np.equal(np.mod(matriz, 3), 0)")
print("Matriz de vedad de valores múltiplos de 3 (matriz_tmp)",
      matriz_tmp, sep="\n")
print()
print("Sentencia: np.sum(matriz_tmp)")
print("Cuenta cuantos valores True hay en la matriz (matriz_tmp).",
      np.sum(matriz_tmp), sep="\n")
print()
print("Sentencia: np.sum(matriz_tmp, axis=0)")
print("Cuenta cuantos valores True hay en cada columna de la matriz (matriz_tmp).",
      np.sum(matriz_tmp, axis=0), sep="\n")
print()
print("Sentencia: np.sum(matriz_tmp, axis=1)")
print("Cuenta cuantos valores True hay en cada fila de la matriz (matriz_tmp).",
      np.sum(matriz_tmp, axis=1), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.equal(np.mod(matriz, 3), 0)
Matriz de vedad de valores múltiplos de 3 (matriz_tmp)
[[False False  True]
 [False False  True]
 [False False  True]]

Sentencia: np.sum(matriz_tmp)
Cuenta cuantos valores True hay en la matriz (matriz_tmp).
3

Sentencia: np.sum(matriz_tmp, axis=0)
Cuenta cuantos valores True hay en cada columna de la matriz (matriz_tmp).
[0 0 3]

Sentencia: np.sum(matriz_tmp, axis=1)
Cuenta cuantos valores True hay en cada fila de la matriz (matriz_tmp).
[1 1 1]

### Reducir

Aplicando operaciones básicas se puede reducir una matriz por filas o por columnas. Las operaciones básicas pueden ser la suma, resta, producto, división, etc.

Esta función retorna un arreglo y su longitud depende de la operación que estoy realizando, es decir, si estoy operando por columnas o por filas.

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.add.reduce(matriz)")
print("Suma los valores de las columnas.",  np.add.reduce(matriz), sep="\n")
print()
print("Sentencia: np.add.reduce(matriz, axis=1)")
print("Suma los valores de las filas.", np.add.reduce(matriz, axis=1), sep="\n")
print()
print("Sentencia: np.multiply.reduce(matriz)")
print("Multiplica los valores de las columnas.",  np.multiply.reduce(matriz), sep="\n")
print()
print("Sentencia: np.multiply.reduce(matriz, axis=1)")
print("Multiplica los valores de las filas.", np.multiply.reduce(matriz, axis=1), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.add.reduce(matriz)
Suma los valores de las columnas.
[12 15 18]

Sentencia: np.add.reduce(matriz, axis=1)
Suma los valores de las filas.
[ 6 15 24]

Sentencia: np.multiply.reduce(matriz)
Multiplica los valores de las columnas.
[ 28  80 162]

Sentencia: np.multiply.reduce(matriz, axis=1)
Multiplica los valores de las filas.
[  6 120 504]

### Acumular

Aplicando operaciones básicas se pueden acumular los valores de una matriz por filas o por columnas. Las operaciones básicas pueden ser la suma, resta, producto, división, etc.  

Esta función retorna una matriz del mismo tamaño a la matriz que realiza la operación.

In [ ]:
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.add.accumulate(matriz)")
print("Suma los valores de las columnas.",  np.add.accumulate(matriz), sep="\n")
print()
print("Sentencia: np.add.accumulate(matriz, axis=1)")
print("Suma los valores de las filas.", np.add.accumulate(matriz, axis=1), sep="\n")
print()
print("Sentencia: np.multiply.accumulate(matriz)")
print("Multiplica los valores de las columnas.",  np.multiply.accumulate(matriz), sep="\n")
print()
print("Sentencia: np.multiply.accumulate(matriz, axis=1)")
print("Multiplica los valores de las filas.", np.multiply.accumulate(matriz, axis=1), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.add.accumulate(matriz)
Suma los valores de las columnas.
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

Sentencia: np.add.accumulate(matriz, axis=1)
Suma los valores de las filas.
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]

Sentencia: np.multiply.accumulate(matriz)
Multiplica los valores de las columnas.
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]

Sentencia: np.multiply.accumulate(matriz, axis=1)
Multiplica los valores de las filas.
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]

## Agregaciones

Estás funciones trabajan sobre 1 matriz realizando las siguientes operaciones.

Las funciones sin el argumentos `axis` realizan el cálculo para toda la matriz, si `axis=0` entonces realiza el cálculo por columnas y si `axis=1` entonces realiza el cálculo por filas.

| Función | Función segura contra nulos | Descripción |
| --- | --- | --- |
| np.sum | np.nansum | Suma los elementos |
| np.prod | np.nanprod | Multiplica los elementos |
| np.mean | np.nanmean | Calcula el promedio de los elementos |
| np.std | np.nanstd | Calcula la desviación estandar de los elementos |
| np.var | np.nanvar | Calcula la varianza de los elementos |
| np.min | np.nanmin | Encuentra el mínimo de los elementos |
| np.max | np.nanmax | Encuentra el máximo de los elementos |
| np.argmin | np.nanargmin | Encuentra el índice del valor mínimo |
| np.argmax | np.nanargmax | Encuentra el máximo del valor máximo |
| np.median | np.nanmedian | Calcula la mediana de los elementos |
| np.percentile | np.nanpercentile | Calcula el percentil de los elementos |

In [ ]:
# Ejemplo de suma
print("Matriz de trabajo (matriz):", matriz, sep="\n")
print()
print("Sentencia: np.sum(matriz)")
print("Suma todos los valores de la matriz:", np.sum(matriz), sep="\n")
print()
print("Sentencia: np.sum(matriz, axis=0)")
print("Suma los valores de la matriz por columnas.", np.sum(matriz, axis=0), sep="\n")
print()
print("Sentencia: np.sum(matriz, axis=1)")
print("Suma los valores de la matriz por filas.", np.sum(matriz, axis=1), sep="\n")
print()
print("Sentencia: np.prod(matriz)")
print("Multiplica todos los valores de la matriz.", np.prod(matriz), sep="\n")
print()
print("Sentencia: np.prod(matriz, axis=0)")
print("Multiplica los valores de la matriz por columnas.", np.prod(matriz, axis=0), sep="\n")
print()
print("Sentencia: np.prod(matriz, axis=1)")
print("Filas los valores de la matriz por filas.", np.prod(matriz, axis=1), sep="\n")

Matriz de trabajo (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sentencia: np.sum(matriz)
Suma toda la matriz.
45

Sentencia: np.sum(matriz, axis=0)
Suma por columnas.
[12 15 18]

Sentencia: np.sum(matriz, axis=1)
Suma por filas.
[ 6 15 24]

Sentencia: np.prod(matriz)
Multiplica todos los valores de la matriz.
362880

Sentencia: np.prod(matriz, axis=0)
Multiplica por columnas.
[ 28  80 162]

Sentencia: np.prod(matriz, axis=1)
Filas por filas.
[  6 120 504]

## Ordenamiento

Permite ordenar los valores de un arreglo o una matriz por filas o por columnas.

In [ ]:
arreglo_tmp = np.random.randint(1,50,6)
print("Matriz de trabajo (arreglo_tmp):", arreglo_tmp, sep="\n")
print()
print("Sentencia: np.sort(arreglo_tmp)")
print("Orden ascendente.", np.sort(arreglo_tmp), sep="\n")
print()
print("Sentencia: np.sort(arreglo_tmp)[::-1]")
print("Orden descendente.", np.sort(arreglo_tmp)[::-1], sep="\n")

Matriz de trabajo (arreglo_tmp):
[37 43 17 35 38 46]

Sentencia: np.sort(arreglo_tmp)
Orden ascendente.
[17 35 37 38 43 46]

Sentencia: np.sort(arreglo_tmp)[::-1]
Orden descendente.
[46 43 38 37 35 17]

In [ ]:
matriz_tmp = np.random.randint(1,50,(4,4))
print("Matriz de trabajo (matriz_tmp):", matriz_tmp, sep="\n")
print()
print("Sentencia: np.sort(matriz_tmp, axis=0)")
print("Orden por columnas.", np.sort(matriz_tmp, axis=0), sep="\n")
print()
print("Sentencia: np.sort(matriz_tmp, axis=1)")
print("Orden por filas.", np.sort(matriz_tmp, axis=1), sep="\n")

Matriz de trabajo (matriz_tmp):
[[11 21 30 22]
 [37  9 46 29]
 [14 10 42  8]
 [11 45  2 48]]

Sentencia: np.sort(matriz_tmp, axis=0)
Orden por columnas.
[[11  9  2  8]
 [11 10 30 22]
 [14 21 42 29]
 [37 45 46 48]]

Sentencia: np.sort(matriz_tmp, axis=1)
Orden por filas.
[[11 21 22 30]
 [ 9 29 37 46]
 [ 8 10 14 42]
 [ 2 11 45 48]]

## Vectorización de funciones

Estos procesos me permiten vectorizar funciones y por lo tanto las puedo aplicar a los vectores o las matrices de numpy.

In [ ]:
# frompyfunc: Vectoriza funciones base de python
base = np.array([2, 3, 4])
exponente = np.array([5, 6, 7])
# array con la función de python pow
# pow recibe como parámetros la base y el exponente
# nin: es la cantidad de parámetros que recibe la función pow
# nout: es la cantidad de resultados que devuelve la función pow
#
vectorizacion_de_la_funcion_pow = np.frompyfunc(pow, nin=2, nout=1)
resultado = vectorizacion_de_la_funcion_pow(base, exponente)

print("Base: \n", base)
print()
print("Exponente: \n", exponente)
print()
print("Resultado: \n", resultado)
print()
print("Operación y resultado:\n")
for b,e,r in zip(base, exponente, resultado):
  print(f"{b} ^ {e} = {r}")

Base:
 [2 3 4]

Exponente:
 [5 6 7]

Resultado:
 [32 729 16384]

Operación y resultado:

2 ^ 5 = 32
3 ^ 6 = 729
4 ^ 7 = 16384

In [ ]:
# vectorize: Vectoriza cualquier función definida por el usuario
def sqrt(base:float, exponente:float)->float:
  return pow(base, 1/exponente)

base = np.array([25, 216, 2401])
exponente = np.array([2, 3, 4])
# array con la función raiz definida por el usuario
vectorizacion_de_la_funcion_sqrt = np.vectorize(sqrt)
resultado = vectorizacion_de_la_funcion_sqrt(base, exponente)
print("Base: \n", base)
print()
print("Exponente: \n", exponente)
print()
print("Resultado: \n", resultado)
print()
print("Operación y resultado:\n")
for b,e,r in zip(base, exponente, resultado):
  print(f"{b} ^ (1/{e}) = {r}")

Base:
 [  25  216 2401]

Exponente:
 [2 3 4]

Resultado:
 [5. 6. 7.]

Operación y resultado:

25 ^ (1/2) = 5.0
216 ^ (1/3) = 5.999999999999999
2401 ^ (1/4) = 7.0
25 216 2401